Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;


namespace CS330_Fall2024_FinalProject.Controllers
{
    public class RoleController : Controller{
        
        //[Authorize(Policy = "AthleteOnly")] //Once it sees this tag, it will go to program.cs to check for the requirements of the athlete only policy
        [Authorize(Roles = $"{Constants.Roles.Athlete}")]
        public IActionResult Index(){
            return View();
        }

      //  [Authorize(Policy = "RequireManager")]
        //[Authorize(Roles = "Coach,Manager")] //Alternate way to do this
           [Authorize(Roles = $"{Constants.Roles.Manager}")]
        public IActionResult Manager()
        {
            return View();
        }

        // [Authorize(Policy = "RequireCoach")]
         [Authorize(Roles = $"{Constants.Roles.Coach}")]
         public IActionResult Coach()
        {
            return View();
        }
    }
}

Controllers/RosterController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CS330_Fall2024_FinalProject.Models;

namespace CS330_Fall2024_FinalProject.Controllers;

public class RosterController : Controller
{
    private readonly AthleteApplicationService _applicationService;

    public RosterController(AthleteApplicationService applicationService)
    {
        _applicationService = applicationService;
    }

    public async Task<IActionResult> Index()
    {
        var athletes = await _applicationService.GetAllAthletesAsync();
        var rosterViewModel = new RosterViewModel()
        {
            Athletes = athletes.Select(a => new CreateAthleteViewModel
            {
                Name = a.Name,
                Number = a.Number,
                Id = a.Id,
                ProfilePictureBytes = a.ProfilePicture,
                Birthday = a.Birthday,
                SkiLevel = a.SkiLevel,
                BestTime = a.Stats?.BestTime ?? 0,
                TopSpeed = a.Stats?.TopSpeed ?? 0,
                BestDistance = a.Stats?.BestDistance ?? 0,
                VerticalDrop = a.Stats?.VerticalDrop ?? 0,
                Ranking = a.Stats?.Ranking ?? 0 

            }).ToList()
        };


        return View(rosterViewModel);

    }
    

    [HttpPost]
    public async Task<IActionResult> DeleteAthlete(int id)
    {
        await _applicationService.DeleteAthleteAsync(id);
        return RedirectToAction("Index");
    }

}

Controllers/ScheduleController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CS330_Fall2024_FinalProject.Models;

namespace CS330_Fall2024_FinalProject.Controllers;

public class ScheduleController : Controller
{
    private readonly IScheduleService _scheduleService;

    public ScheduleController(IScheduleService scheduleService)
    {
        _scheduleService = scheduleService;
    }

    public async Task<IActionResult> Index()
    {
        var schedules = await _scheduleService.GetAllAsync();

        return View(schedules);
    }

    [HttpGet]
    //[Authorize(Roles = "Coach,Manager")]
    //OR?
    //[Authorize(Policy = "RequireCoach")]
    //[Authorize(Policy = "RequireManager")]
    public IActionResult Create()
    {
        var schedule = new Schedule
        {
            Date = DateTime.Now
        };
        return View();
    }

    [HttpPost]
    //[Authorize(Roles = "Coach,Manager")]
    //OR?
    //[Authorize(Policy = "RequireCoach")]
    //[Authorize(Policy = "RequireManager")]
    public async Task<IActionResult> Create(Schedule schedule, string Time)
    {
        if (ModelState.IsValid)
        {
            if (DateTime.TryParse(schedule.Date.ToString("yyyy-MM-dd") + " " + Time, out DateTime combinedDateTime))
            {
                schedule.Date = combinedDateTime;
                await _scheduleService.AddAsync(schedule);
                return RedirectToAction(nameof(Index));
            }

            ModelState.AddModelError("", "Invalid date or time format.");
        }
        return View(schedule);
    }
}

Controllers/StatsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CS330_Fall2024_FinalProject.Models;
using CS330_Fall2024_FinalProject.Repositories;
using Microsoft.EntityFrameworkCore;
using CS330_Fall2024_FinalProject.Data;

// not same as SkiStats stuff but should prob pull in SkiStats stuff in here

namespace CS330_Fall2024_FinalProject.Controllers;


public class StatsController : Controller
{

    private readonly SkiStatsRepository _skiStatsRepository;

    // private readonly ApplicationDbContext? _context;

    public StatsController(SkiStatsRepository skiStatsRepository)
    {
        _skiStatsRepository = skiStatsRepository;
    }
    public IActionResult Index()
    {

        var records = new List<SkiStatsViewModel>
        {
            new SkiStatsViewModel
            {
                StatName = "Best Time",
                Value = _skiStatsRepository.GetBestTime().Value,
                AthleteName = _skiStatsRepository.GetBestTime().AthleteName
            },
            new SkiStatsViewModel
            {
                StatName = "Top Speed",
                Value = _skiStatsRepository.GetTopSpeed().Value,
                AthleteName = _skiStatsRepository.GetTopSpeed().AthleteName
            },
            new SkiStatsViewModel
            {
                StatName = "Best Distance",
                Value = _skiStatsRepository.GetBestDistance().Value,
                AthleteName = _skiStatsRepository.GetBestDistance().AthleteName
            },
            new SkiStatsViewModel
            {
                StatName = "Vertical Drop",
                Value = _skiStatsRepository.GetVerticalDrop().Value,
                AthleteName = _skiStatsRepository.GetVerticalDrop().AthleteName
            }
        };

        var avg = _skiStatsRepository.GetTeamAverages();

        var vm = new TeamStatsViewModel
        {
            TeamRecords = records,
            TeamAverages = avg
        };

        return View(vm);
    }

    public IActionResult ViewAthleteStats(string id)
    {

        //Console.WriteLine($"Received Athlete ID: {id}");
        var athleteProfile = _skiStatsRepository.GetAthleteProfile(id);

        var athleteStats = new List<SkiStatsViewModel>
        {
            new SkiStatsViewModel
            {
                StatName = "Best Time",
                Value = _skiStatsRepository.GetAthleteBestTime(id).Value,
                AthleteName = _skiStatsRepository.GetAthleteBestTime(id).AthleteName,
                ProfilePictureBytes = athleteProfile.ProfilePictureBytes 
            },
            new SkiStatsViewModel
            {
                StatName = "Top Speed",
                Value = _skiStatsRepository.GetAthleteTopSpeed(id).Value,
                AthleteName = _skiStatsRepository.GetAthleteTopSpeed(id).AthleteName,
                ProfilePictureBytes = athleteProfile.ProfilePictureBytes 
            },
            new SkiStatsViewModel
            {
                StatName = "Best Distance",
                Value = _skiStatsRepository.GetAthleteBestDistance(id).Value,
                AthleteName = _skiStatsRepository.GetAthleteBestDistance(id).AthleteName,
                ProfilePictureBytes = athleteProfile.ProfilePictureBytes 
            },
            new SkiStatsViewModel
            {
                StatName = "Vertical Drop",
                Value = _skiStatsRepository.GetAthleteVerticalDrop(id).Value,
                AthleteName = _skiStatsRepository.GetAthleteVerticalDrop(id).AthleteName,
                ProfilePictureBytes = athleteProfile.ProfilePictureBytes 
            }
        };

        return View(athleteStats);
    }



}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

@using Microsoft.AspNetCore.Identity
@inject SignInManager<Athlete> SignInManager
@inject UserManager<Athlete> UserManager

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Snow Ski</title>

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Fonts -->
    @* <link href="https://fonts.googleapis.com" rel="preconnect">  *@
    @* <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin> *@
    @* <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"> *@
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" integrity="sha384-Gi4LDFCfmiT9UQ5COrpdV7KHx8ceZD3cShsGebDxorHAkpoT5BvbUJsFsDFcCU6b" crossorigin="anonymous" rel="stylesheet">
    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Main CSS File -->
    <link href="~/assets/css/main.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Squadfree
    * Template URL: https://bootstrapmade.com/squadfree-free-bootstrap-template-creative/
    * Updated: Aug 07 2024 with Bootstrap v5.3.3
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->

    @* <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> *@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/CS330_Fall2024_FinalProject.styles.css" asp-append-version="true" /> *@

</head>


<body>
    @* <header id="header" class="header d-flex align-items-center fixed-top"> *@
    <header id="header" class="header d-flex align-items-center fixed-top @((ViewContext.RouteData.Values["controller"]?.ToString() == "Home" && ViewContext.RouteData.Values["action"]?.ToString() == "Index") ? "navbar-home" : "navbar-other")">
        <!--<nav id="navbar-section" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">-->
            <div class="container-fluid container-xl position-relative d-flex align-items-center justify-content-between">
                <!-- Logo Section -->
                <a asp-area="" asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center">
                    <h1 class="sitename">Snow Ski Team</h1>
                </a>
                <!-- Navbar Section -->
                <nav id="navmenu" class="navmenu">
                    <ul>
                        <!-- Standard Links -->
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Schedule" asp-action="Index">Schedule</a></li>
                       

                        <!-- Role-Based Links -->
                        @if (User.Identity?.IsAuthenticated == true)
                        {
                            if (User.IsInRole("Athlete") && User.IsInRole("Manager") && User.IsInRole("Coach"))
                            {
                                <!-- Dropdown for multiple roles -->
                                 <li><a asp-controller="Stats" asp-action="Index">Stats</a></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                                        Role Pages <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a asp-controller="Role" asp-action="Index">Athletes Page</a></li>
                                        <li><a asp-controller="Role" asp-action="Coach">Coach's Page</a></li>
                                        <li><a asp-controller="Role" asp-action="Manager">Manager's Page</a></li>
                                        <li><a asp-controller="Athlete" asp-action="Index">Manage Users</a></li>
                                    </ul>
                                </li>
                            }
                            else if (User.IsInRole("Athlete") && User.IsInRole("Manager")){
                                 <li><a asp-controller="Stats" asp-action="Index">Stats</a></li>
                                <!-- Dropdown for multiple roles -->
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                                        Role Pages <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a asp-controller="Role" asp-action="Index">Athletes Page</a></li>
                                        <li><a asp-controller="Role" asp-action="Manager">Manager's Page</a></li>
                                        @* <li><a asp-controller="ManageRoles" asp-action="Index">Manage Roles</a></li> *@
                                    </ul>
                                </li>
                            }
                            else if (User.IsInRole("Athlete") && User.IsInRole("Coach")){
                                <!-- Dropdown for multiple roles -->
                                 <li><a asp-controller="Stats" asp-action="Index">Stats</a></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                                        Role Pages <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a asp-controller="Role" asp-action="Index">Athletes Page</a></li>
                                        <li><a asp-controller="Role" asp-action="Coach">Coach's Page</a></li>
                                        <li><a asp-controller="Role" asp-action="Manager">Manager's Page</a></li>
                                        <li><a asp-controller="Athlete" asp-action="Index">Manage Users</a></li>
                                    </ul>
                                </li>
                            }
                            else
                            {
                                <!-- Individual Role Links -->
                                @if (User.IsInRole("Athlete"))
                                {
                                    <li><a asp-controller="Role" asp-action="Index">Athletes Page</a></li>
                                     <li><a asp-controller="Stats" asp-action="Index">Stats</a></li>
                                }
                                @if (User.IsInRole("Coach"))
                                {
                                     <li><a asp-controller="Stats" asp-action="Index">Stats</a></li>
                                    <li><a asp-controller="Role" asp-action="Coach">Coach's Page</a></li>
                                    <li><a asp-controller="Athlete" asp-action="Index">Manage Roles</a></li>
                                }
                                @if (User.IsInRole("Manager"))
                                {
                                     <li><a asp-controller="Stats" asp-action="Index">Stats</a></li>
                                    <li><a asp-controller="Role" asp-action="Manager">Manager's Page</a></li>
                                }
                            }
                        }

                        <!-- Additional Links -->
                  
                        <li><a asp-controller="Roster" asp-action="Index">Roster</a></li>

                        <!-- Login/Logout/Register Links -->
                        <li>
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <li>
                                    <a asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity?.Name!</a>
                                </li>
                                <li>
                                    <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                        <button type="submit" class="nav-link btn btn-link">Logout</button>
                                    </form>
                                </li>
                            }
                            else
                            {
                                <li>
                                    <a asp-area="Identity" asp-page="/Account/Register">Register</a>
                                </li>
                                <li>
                                    <a asp-area="Identity" asp-page="/Account/Login">Login</a>
                                </li>
                            }
                        </li>
                    </ul>

                    <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
                </nav>

            </div>
        <!--</nav> -->
    </header> 

    <div class="container"></div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <!-- Chat Bot Button on bottom right  -->
    <button id="chat-bot-button"
        class="btn2 btn-primary btn2-chat border border-1 shadow-lg d-flex align-items-center justify-content-center"
        onclick="goToChatBot()">
        <img id="chat-bot-button-icon" src="~/Images/chatbot-icon.svg" alt="ChatBot Icon" />
    </button>

    <footer id="footer" class="footer dark-background py-3">
        <div class="container footer-top">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6 footer-about d-flex align-items-center">
                    <a href="~/" class="logo d-flex align-items-center">
                        <h1 class="sitename me-3">Snow Ski</h1>
                    </a>
                </div>
                <div class="col-lg-6 col-md-6 text-end">
                    <p class="mb-0">
                        This website is built by Anastasia Spencer, Brooke Boskus, Collin Price, Owen McMenaman, and Jeongbin Son for CS 330 - Final Project.
                    </p>                
                </div>
            </div>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/js/main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
    @* style="display: none;" *@
    @* i cant figure out how to make this button only show up when the user has scrolled 300 pixels down *@
    @* <button id="scrollToTopButton" class="scroll-to-top" onclick="scrollToTop()"  > 
    ↑
    </button> *@

</body>

</html>

Views/Shared/_LayoutOriginal.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Snow Ski</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> 
    <!-- Need to add Hashing to this link-->

    @* <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> *@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/CS330_Fall2024_FinalProject.styles.css" asp-append-version="true" /> *@

</head>


<body>
    <header>
        <nav id="navbar-section"
            class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Snow Ski</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Schedule"
                                asp-action="Index">Schedule</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stats"
                                asp-action="Index">Stats</a>
                        </li>
                        <li class="nav-item">
                            @if (User.Identity?.IsAuthenticated == true)
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Athletes Page</a> <!-- athletes only page -->
                            }
                        </li>
                        <!-- what we can do here is add another one for athletes only, to differentiate justify-content-between not logged in button logged in with the lowest permissions  -->
                        <li class="nav-item">
                            @if (User.Identity?.IsAuthenticated == true && User.IsInRole("Coach"))
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Coach">Coachs Page</a> <!-- coach only page -->
                            }
                        </li>
                        <li class="nav-item">
                            @if (User.Identity?.IsAuthenticated == true && User.IsInRole("Manager"))
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Manager">Manager Page </a> <!-- mananger only page -->
                            }
                        </li>
                 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roster"
                                asp-action="Index">Roster</a>
                        </li>
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header> 

    <div class="container min-vh-100 d-flex flex-column positive-relative">
        <main role="main" class="pb- flex-grow-1">
            @RenderBody()
        </main>
    </div>

    <!-- Chat Bot Button on bottom right  -->
    <button id="chat-bot-button"
        class="btn2 btn-primary btn2-chat shadow-lg d-flex align-items-center justify-content-center"
        onclick="goToChatBot()">
        <img id="chat-bot-button-icon" src="~/Images/chatbot-icon.svg" alt="ChatBot Icon" />
    </button>


    <footer id="footer-section" class="border-top footer text-muted text-center mt-auto">
        <div class="container">
            This website is built by Anastasia Spencer, Brooke Boskus, [], [], and Jeongbin Son for CS 330 - Final
            Project
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>